#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 192.168.190.10
    #redis 端口
    port: 6379
    #redis 密码
    password: Poiuy123
    #redis 数据库
    database: 10
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.190.10:3306/wms_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    #MySQL账号
    username: root
    #MySQL密码
    password: root

#blade配置
blade:
  prop:
    upload-domain: http://114.215.129.212:8888
    remote-mode: true
    log-mode: true
server:
  #启动端口
  port: 8088
