#天宜测试环境配置
spring:
  redis:
    host: 192.168.41.173
    port: 6379
    password:
    database: 1
    ssl: false
  datasource:
    url: jdbc:mysql://192.168.41.172:3306/qa_wms?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: Nodes@2022#
